backend/system/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views import static

from system.features.game import TakePartInGameView, GamesView, GameInfoView, PlayGameView, PlayGameLevelView, \
    FinishGameView, GameStatisticView, GameStatusView
from system.features.teams import MyTeamView, CreateTeamView, InviteToTeamView, DeleteInvitationView, \
    AcceptInvitationView, TeamView, UserView
from system.views import auth_logout, HomeView, SetLangView, RegisterView, ProfileView

urlpatterns = [
    url(r'^$', login_required(HomeView.as_view()), name="home"),

    url(r'^user/(?P<user_id>\d+)/info/$', login_required(UserView.as_view()), name="user"),

    url(r'^my/team/$', login_required(MyTeamView.as_view()), name="my_team"),
    url(r'^team/new/$', login_required(CreateTeamView.as_view()), name="create_team"),
    url(r'^team/(?P<team_id>\d+)/info/$', login_required(TeamView.as_view()), name="team"),
    url(r'^team/(?P<team_id>\d+)/invite/$', login_required(InviteToTeamView.as_view()), name="invite_to_team"),
    url(r'^team/delete_invite/(?P<id>\d+)/$', login_required(DeleteInvitationView.as_view()), name="delete_invite"),
    url(r'^team/accept_invite/(?P<id>\d+)/$', login_required(AcceptInvitationView.as_view()), name="accept_invite"),

    url(r'^games/$', login_required(GamesView.as_view()), name="games"),
    url(r'^game/(?P<game_id>\d+)/info/$', login_required(GameInfoView.as_view()), name="game_info"),
    url(r'^game/(?P<game_id>\d+)/take_part/$', login_required(TakePartInGameView.as_view()), name="take_part_in_game"),
    url(r'^game/(?P<game_id>\d+)/play/$', login_required(PlayGameView.as_view()), name="play_game"),
    url(r'^game/(?P<game_id>\d+)/level/(?P<level>\d+)/play/$', login_required(PlayGameLevelView.as_view()),
        name="play_level"),
    url(r'^game/(?P<game_id>\d+)/finish/$', login_required(FinishGameView.as_view()), name="finish_game"),
    url(r'^game/(?P<game_id>\d+)/statistics/$', login_required(GameStatisticView.as_view()), name="game_stats"),
    url(r'^game/(?P<game_id>\d+)/status/$', login_required(GameStatusView.as_view()), name="game_status"),

    url(r'^accounts/login/', auth_views.login, name="my_login"),
    url(r'^accounts/logout/$', auth_logout, name="logout"),
    url(r'^accounts/profile/$', ProfileView.as_view(), name="profile"),
    url(r'^accounts/register/$', RegisterView.as_view(), name="register"),
    url(r'^set_language/$', SetLangView.as_view(), name='set_language'),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
]

backend/system/models.py
# coding=utf-8
import json
import os
import random
from datetime import datetime, timedelta

from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils import translation, timezone
from django.utils.translation import ugettext_lazy as _


class Team(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"Название", unique=True)
    created_at = models.DateField(auto_now_add=True, verbose_name=u"Дата создания")
    created_by = models.ForeignKey(User, verbose_name=u"Создатель", null=True, blank=True, on_delete=models.SET_NULL,
                                   related_name="my_teams")

    def captain(self):
        caps = self.members.filter(is_cap=True)
        if caps.count() > 0:
            return caps.first().user
        return None

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"Команды"
        verbose_name = u"Команда"


class UserDetails(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=u"Пользователь", related_name="details")
    phone_number = models.CharField(max_length=100, verbose_name=u"Номер телефона", null=True, blank=True)
    current_team = models.ForeignKey(Team, null=True, blank=True, verbose_name=u"Текущая команда",
                                     on_delete=models.SET_NULL, related_name="members")
    is_cap = models.BooleanField(default=False, verbose_name=u"Капитан своей команды")
    weight = models.IntegerField(null=True, blank=True, verbose_name=u"Вес(кг)")
    height = models.IntegerField(null=True, blank=True, verbose_name=u"Роск(см)")
    sex = models.CharField(default="male", choices=[["male", u"Мужской"], ["female", u"Женский"]], verbose_name=u"Пол",
                           max_length=10)

    def __unicode__(self):
        return unicode(self.user)

    @staticmethod
    def of(user):
        details, _ = UserDetails.objects.get_or_create(user=user)
        return details

    class Meta:
        verbose_name_plural = u"Детали пользователей"
        verbose_name = u"Детали пользователя"


class Invitation(models.Model):
    team = models.ForeignKey(Team, verbose_name=u"В команду", related_name="invitations")
    user = models.ForeignKey(User, verbose_name=u"Кого", related_name="invitations")

    class Meta:
        verbose_name_plural = u"Приглашения в команду"
        verbose_name = u"Приглашение в команду"


class Game(models.Model):
    author = models.ForeignKey(User, verbose_name=u"Автор игры", related_name="my_games")
    title = models.CharField(max_length=255, verbose_name=u"Название")
    content = RichTextField(verbose_name=u"Описание")
    active = models.BooleanField(verbose_name=u"Игра доступна", default=False)
    min_players = models.IntegerField(verbose_name=u"Минимальное кол-во игроков", default=0, null=True, blank=True)
    max_players = models.IntegerField(verbose_name=u"Максимальное кол-во игроков", default=0, null=True, blank=True)
    starts_at = models.DateTimeField(verbose_name=u"Время начала")
    finishes_at = models.DateTimeField(verbose_name=u"Время конца", null=True, blank=True)
    finished = models.BooleanField(default=False, verbose_name=u"Закончен")
    status = models.CharField(max_length=20, default="not_started", verbose_name=u"Состояние", choices=[
        ["not_started", u"Не начат"], ["started", u"Идет"], ["scoring", u"Подсчет очков"], ["finished", u"Закончен"],
    ])
    sequence = models.CharField(max_length=20, verbose_name=u"Последовательность", default="linear", choices=[
        ["linear", u"Линейная"], ["random", u"Штурмовая"]
    ])

    def ready_to_start(self):
        seconds_to_start = (self.starts_at - timezone.now()).total_seconds()
        return seconds_to_start < 300.0

    def starts_in(self):
        seconds_to_start = (self.starts_at - timezone.now()).total_seconds()
        return int(max(seconds_to_start, 0))

    def has_next_level(self, level):
        return self.levels.filter(order__gt=level.order).exists()

    def get_next_level(self, level):
        return self.levels.filter(order__gt=level.order).first()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = u"Игры"
        verbose_name = u"Игра"
        ordering = ["starts_at"]


class GameLevel(models.Model):
    game = models.ForeignKey(Game, verbose_name=u"Игры", related_name="levels")
    order = models.IntegerField(default=0, verbose_name=u"Уровень")
    title = models.CharField(max_length=255, verbose_name=u"Название уровня")
    content = RichTextField(verbose_name=u"Текст задания")
    right_answers = models.TextField(verbose_name=u"Правильные ответы(json array)")
    auto_close_time = models.IntegerField(verbose_name=u"Время автоперехода(мин)", default=0)

    def is_answer_right(self, answer):
        answers = json.loads(self.right_answers)
        if answer and answer in answers:
            return True
        return False

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = u"Уровни игры"
        verbose_name = u"Уровень игры"
        ordering = ["game", "order"]


class Hint(models.Model):
    level = models.ForeignKey(GameLevel, verbose_name=u"Уровень игры")
    content = RichTextField(verbose_name=u"Текст подсказки")
    available_in = models.IntegerField(verbose_name=u"Доступна через(мин)", default=0)
    penalty = models.IntegerField(verbose_name=u"Штрафное время(мин)", default=0)

    def __unicode__(self):
        return u"Подсказка к уровню '%s'" % self.level.title

    class Meta:
        verbose_name_plural = u"Подсказки"
        verbose_name = u"Подсказка"
        ordering = ["level", "available_in"]


class Bonus(models.Model):
    level = models.ForeignKey(GameLevel, verbose_name=u"Уровень игры")
    order = models.IntegerField(default=0, verbose_name=u"Порядок")
    title = models.CharField(max_length=255, verbose_name=u"Название бонуса")
    content = RichTextField(verbose_name=u"Текст задания бонуса")
    bonus_time = models.IntegerField(verbose_name=u"Бонусное время(мин)", default=0)
    right_answers = models.TextField(verbose_name=u"Правильные ответы(json array)")

    def __unicode__(self):
        return u"Бонус №%d '%s'" % (self.order, self.title)

    class Meta:
        verbose_name_plural = u"Бонусы"
        verbose_name = u"Бонус"
        ordering = ["level", "order"]


class TeamInGame(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name=u"Игра", related_name="teams")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name=u"Команда", related_name="games")
    finished = models.BooleanField(default=False, verbose_name=u"Закончили игру")

    class Meta:
        verbose_name_plural = u"Команды в игре"
        verbose_name = u"Команда в игре"


class PlayerInGame(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name=u"Игра", related_name="players")
    team = models.ForeignKey(Team, null=True, blank=True, on_delete=models.CASCADE, verbose_name=u"В составе команды")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=u"Игрок", related_name="games")

    class Meta:
        verbose_name_plural = u"Игроки в игре"
        verbose_name = u"Игрок в игре"


class LevelStat(models.Model):
    level = models.ForeignKey(GameLevel, verbose_name=u"Уровень", related_name="stats", on_delete=models.CASCADE)
    team = models.ForeignKey(Team, verbose_name=u"Команда", on_delete=models.CASCADE)
    started_at = models.DateTimeField(auto_now_add=True, verbose_name=u"Время начала уровня")
    finished_at = models.DateTimeField(verbose_name=u"Время конца уровня", null=True, blank=True)
    time_in_level = models.IntegerField(verbose_name=u"Время на уровне(сек)", default=0)
    total_penalty = models.IntegerField(verbose_name=u"Штрафов на уровне(сек)", default=0)
    total_bonus = models.IntegerField(verbose_name=u"Бонусов на уровне(сек)", default=0)

    def __unicode__(self):
        return unicode(self.level)

    class Meta:
        verbose_name_plural = u"Статистика команд на уровнях"
        verbose_name = u"Статистика команды на уровне"
        ordering = ["level__order"]


class Answer(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=u"Время ответа")
    level_stat = models.ForeignKey(LevelStat, verbose_name=u"Уровень", related_name="answers", on_delete=models.CASCADE)
    answer = models.CharField(max_length=1000, verbose_name=u"Ответ")
    user = models.ForeignKey(User, verbose_name=u"Кто отправил")
    right = models.BooleanField(default=False, verbose_name=u"Правильный")
    bonus_time = models.IntegerField(verbose_name=u"Бонус(сек)", default=0)

    def __unicode__(self):
        return unicode(self.answer)

    class Meta:
        verbose_name_plural = u"Ответы"
        verbose_name = u"Ответ"

backend/system/forms.py
# coding=utf-8
from datetime import time

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import Form
from django.forms.models import ModelForm
from django.forms.widgets import TextInput, NumberInput
from django.utils.translation import ugettext_lazy as _

from system.models import Team


class RegistrationForm(ModelForm):
    username = forms.SlugField(required=True, label=u"Имя пользователя")
    email = forms.EmailField(required=True, label=u"Email")
    first_name = forms.CharField(required=False, label=u"Имя")
    last_name = forms.CharField(required=False, label=u"Фамилия")
    phone_number = forms.CharField(required=False, label=u"Номер телефона")
    weight = forms.IntegerField(required=False, label=u"Ваш вес")
    height = forms.IntegerField(required=False, label=u"Ваш рост")
    sex = forms.ChoiceField(required=True, choices=[["male", u"Мужской"], ["female", u"Женский"]], label=u"Ваш пол",
                            widget=forms.Select)
    password = forms.CharField(required=True, widget=forms.PasswordInput, label=u"Придумайте пароль")
    password_repeat = forms.CharField(required=True, widget=forms.PasswordInput, label=u"Повторите пароль")

    def clean_password(self):
        password = self.data["password"]
        if len(password) < 8:
            raise ValidationError(u"Пароль должен быть не менее 8 символов")
        return password

    def clean_password_repeat(self):
        if self.data["password"] != self.data["password_repeat"]:
            raise ValidationError(u"Пароли не совпадают")
        return self.data["password_repeat"]

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ['name']

backend/system/views.py
# coding=utf-8
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import user_passes_test
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import translation
from django.views.generic import TemplateView
from django.utils import timezone
from system.forms import RegistrationForm
from system.models import UserDetails, Game


def auth_logout(request):
    logout(request)
    return redirect(reverse("home"))


class HasPermMixin(object):
    required_permissions = []

    @staticmethod
    def has_perms(permissions, user):
        for permission in permissions:
            if not user.has_perm(permission):
                return False
        return True

    @classmethod
    def as_view(cls, **initkwargs):
        # type: (object) -> object
        view = super(HasPermMixin, cls).as_view(**initkwargs)
        if not isinstance(cls.required_permissions, list):
            raise Exception("required_permissions must be list of permissions")

        actual_decorator = user_passes_test(
            lambda u: HasPermMixin.has_perms(cls.required_permissions, u),
            login_url="/"
        )

        return actual_decorator(view)


class BaseView(HasPermMixin, TemplateView):
    def dispatch(self, request, *args, **kwargs):
        return super(BaseView, self).dispatch(request, *args, **kwargs)


class HomeView(BaseView):
    template_name = "home.html"

    def dispatch(self, request, *args, **kwargs):
        games_in_progress = Game.objects.filter(active=True, status="started")
        games_in_future = Game.objects.filter(active=True, status="not_started")
        six_hours_ago = timezone.now() - timedelta(hours=6)
        just_finished_games = Game.objects.filter(Q(status="finished") | Q(status="scoring")).filter(
            finishes_at__gt=six_hours_ago, active=True)
        return render(request, self.template_name, {
            'games_in_progress': games_in_progress,
            'games_in_future': games_in_future,
            'just_finished_games': just_finished_games
        })


class RegisterView(BaseView):
    template_name = "registration/register.html"

    def dispatch(self, request, *args, **kwargs):
        form = RegistrationForm()
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                form.save()
                self.save_details(form)
                messages.success(request, u"Вы успешно прошли регистрацию! Войдите используя свой аккаунт")
                return redirect(reverse("my_login"))

        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def save_details(self, form):
        form.instance.set_password(form.cleaned_data['password'])
        form.instance.save()
        details = UserDetails(user=form.instance)
        details.sex = form.cleaned_data["sex"]
        if "phone_number" in form.cleaned_data:
            details.phone_number = form.cleaned_data["phone_number"]
        if "weight" in form.cleaned_data:
            details.weight = form.cleaned_data["weight"]
        if "height" in form.cleaned_data:
            details.height = form.cleaned_data["height"]
        details.save()


class ProfileView(BaseView):
    template_name = "registration/profile.html"


class SetLangView(BaseView):
    def dispatch(self, request, *args, **kwargs):
        old_lang = translation.get_language()
        lang = request.GET.get("language", None)
        if lang in ['ru', 'en']:
            translation.activate(lang)
            request.session[translation.LANGUAGE_SESSION_KEY] = lang
            request.LANGUAGE_CODE = translation.get_language()
        return redirect("/")

backend/system/templates/block/breadcrumb.html
{% load i18n %}

<div>
<ul class="breadcrumb">
    <li><a href="/">{% trans 'Главная'%}</a> <span class="divider">/</span></li>
    <li class="active">{% trans 'О нас'%}</li>
</ul>
</div>

backend/system/templates/block/game.html
{% load staticfiles %}
<div class="ui inverted segment game">
    <img style="max-width: 24px; float: left; margin-right: 10px;" src="{% static 'img/labyrinth.png' %}">
    <a href="{% url 'game_info' game.id %}" class="ui blue header">(#{{ game.id }}) "{{ game.title }}"</a>
    <div style="clear: both;"></div>
    <hr>
    <div class="ui list">
        {% if not game.active %}
            <div class="ui red item">Игра не активна</div>
        {% endif %}
        <div class="item"><b>Играем:</b> Командами</div>
        <div class="item"><b>Последовательность:</b> {{ game.get_sequence_display }}</div>
        <div class="item"><b>Начало игры:</b> {{ game.starts_at|date:"d.m.Y H:i" }}</div>
        <div class="item"><b>Времени осталось:</b> {{ game.starts_at|timeuntil }}</div>
        {% if game.min_players or game.max_players %}
            <div class="item"><b>Ограничение по игрокам:</b>
                от {{ game.min_players|default_if_none:"1" }}
                {% if game.max_players %}
                    до {{ game.max_players }}
                {% endif %} игроков в команде
            </div>
        {% endif %}
    </div>
    <hr>
    {% if game.active and game.status == "not_started" %}
        <form action="{% url 'take_part_in_game' game.id %}" method="post" class="item" style="display: inline-block;">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <button class="ui mini basic orange button">Подать заявку на участие</button>
        </form>
    {% endif %}
    {% if not game.active or game.ready_to_start and not game.finished %}
        <a href="{% url 'play_game' game.id %}" class="ui mini basic labeled green icon button">
            <i class="puzzle icon"></i>
            Перейти к игре
        </a>
    {% endif %}
    {% if game.status != "not_started" %}
        <a href="{% url 'game_stats' game.id %}"
           class="ui basic pink labeled mini icon button">
            <i class="chart bar icon"></i> Статистика
        </a>
    {% endif %}
    <hr>
    <div class="ui list">
        <div class="item">
            <b>Приняты к участию:</b> {{ game.teams.count }} команд:
            {% for participation in game.teams.all %}
                <a href="{% url 'team' participation.team.id %}" class="ui">{{ participation.team.name }}</a>,
            {% endfor %}
        </div>
    </div>
    {% if not short %}
        <hr>
        <div class="game-content">
            {{ game.content|safe }}
        </div>
    {% endif %}
</div>

backend/system/templates/block/messages.html
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            {% if message.tags == "success" %}
                <div class="ui inverted teal message">{{ message }}</div>
            {% elif message.tags == "error" %}
                <div class="ui inverted red message">{{ message }}</div>
            {% elif message.tags == "warning" %}
                <div class="ui inverted orange message">{{ message }}</div>
            {% elif message.tags == "info" %}
                <div class="ui inverted blue message">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

backend/system/templates/block/navbar.html
{% load i18n my_filters %}

<header class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
        <a class="item {% if section == 'home' %}active{% endif %}" href="/">
            {% trans 'Quest Labs' %}
        </a>
        <a class="item {% if section == 'games' %}active{% endif %}" href="{% url 'games' %}">
            {% trans 'Игры' %}
        </a>
        <div class="right menu">

            {% if user.is_authenticated %}
                <a href="{% url 'profile' %}" class="ui black image label item">
                    <img src="{{ user.email|gravatar }}">
                    &nbsp;&nbsp;&nbsp;{{ user.username }}
                </a>
                <a class="item"
                   href="{% url 'logout' %}">Выйти</a>
            {% else %}
                <a class="item"
                   href="{% url 'my_login' %}">Войти</a>
            {% endif %}
        </div>
    </div>
</header>

backend/system/templates/block/pagination.html
{% load i18n %}
<style>
    .pagination {
        font: 14px/24px sans-serif;
    }
    .page {
        display: inline-block;
        padding: 0px 9px;
        border-radius: 3px;
        border: solid 1px #c0c0c0;
        background: #e9e9e9;
        box-shadow: inset 0px 1px 0px rgba(255, 255, 255, .8), 0px 1px 3px rgba(0, 0, 0, .1);
        font-size: .875em;
        font-weight: bold;
        text-decoration: none;
        color: #717171;
        text-shadow: 0px 1px 0px rgba(255, 255, 255, 1);
    }
    .page:hover {
        background: #fefefe;
        background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#FEFEFE), to(#f0f0f0));
        background: -moz-linear-gradient(0% 0% 270deg, #FEFEFE, #f0f0f0);
    }
    .page.active {
        border: none;
        background: #616161;
        box-shadow: inset 0px 0px 8px rgba(0, 0, 0, .5), 0px 1px 0px rgba(255, 255, 255, .8);
        color: #f0f0f0;
        text-shadow: 0px 0px 3px rgba(0, 0, 0, .5);
    }
</style>

<div class="pagination">
{% for page in pages %}
    {% if page == current_page %}
        <span class="page active">{{ page }}</span>
    {% else %}
        {% if page == 'first' %}
            <a href="?page={{ 1 }}&per_page={{ per_page }}" class="page"> {% trans 'первая' %} </a>
        {% elif page == 'last' %}
            <a href="?page={{ last }}&per_page={{ per_page }}" class="page"> {% trans 'последняя' %} </a>
        {% else %}
            <a href="?page={{ page }}&per_page={{ per_page }}" class="page">{{ page }}</a>
        {% endif %}
    {% endif %}
{% endfor %}
</div>

backend/system/templates/block/sex.html
{% load staticfiles %}
{% if sex == 'male' %}
    <img style="height: 16px;" src="{% static 'img/boy.png' %}">
{% else %}
    <img style="height: 16px;" src="{% static 'img/girl.png' %}">
{% endif %}

backend/system/templates/block/side_menu.html
{% load my_filters staticfiles %}
<div class="ui fluid dark card">
    <div class="image" style="max-width: 150px;">
        <img src="{{ user.email|gravatar }}">
    </div>
    <div class="content">
        <a class="header">{{ user.username }}</a>
        <div class="meta">
            <span class="date">{{ user.get_full_name }}</span>
        </div>
        <div class="description">
            <hr>
            <div class="ui inverted link list">
                <a class="item" href="{% url 'profile' %}">Мое личное дело</a>
                <a class="item" href="{% url 'my_team' %}">Моя команда</a>
            </div>
            <hr>
            <div class="ui inverted link list">
                <a class="item" href="{% url 'logout' %}">Выход</a>
            </div>
        </div>
    </div>
</div>

<div class="ui fluid dark card">
    <div class="content">
        <a class="header">Прошедшие игры</a>
        <div class="description">
            <hr>
            {% for game in finished_games %}
                <img style="max-width: 24px; float: left; margin-right: 10px;" src="{% static 'img/labyrinth.png' %}">
                <a href="{% url 'game_info' game.id %}" class="ui blue header">(#{{ game.id }}) "{{ game.title }}"</a>
                <div style="clear: both;"></div>

                <div class="ui list">
                    <div class="item"><b>Начало игры:</b> {{ game.starts_at|date:"d.m.Y H:i" }}</div>
                    <div class="item"><b>Приняли участие:</b> {{ game.teams.count }} команд</div>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>
</div>